#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftM,         tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          RightM,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int wheelDia=3.25;// wheel diameter for calculations
int distance=12; //desired distance
int Ttick=360;//total ticks for 1 rotation
int kP=0.5;//Proportional constant
int kI=0.25;//Integral constant
int kD=0.25;// Derivative constant

void forward(int d){
	int FwdTicks=Ttick*d/(wheelDia*PI);
	resetMotorEncoder(LeftM);
	while(abs(getMotorEncoder(LeftM))< FwdTicks){
		error=FwdTicks-getMotorEncoder(LeftM);
	motor(LeftM)=error;
	motor(RightM)=error;
}
motor(LeftM)=0;
motor(RightM)=0;
}

void turnR(){
  resetMotorEncoder(LeftM);
	while(abs(getMotorEncoder(LeftM))<15){
	motor(LeftM)=60;
	motor(RightM)=-60;
}
motor(LeftM)=0;
motor(RightM)=0;
}
void turnL(){
  resetMotorEncoder(LeftM);
	while(abs(getMotorEncoder(LeftM))<15){
	motor(LeftM)=-60;
	motor(RightM)=60;
}
motor(LeftM)=0;
motor(RightM)=0;
}

task main()
{
	int i;
	for(i=0;i<1000;i++){
	forward(distance);
    wait1Msec(2000);
	//turnR();
}
}
