#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftM,         tmotorVex393HighSpeed_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          RightM,        tmotorVex393HighSpeed_HBridge, openLoop, reversed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int wheelDia=3.25;// wheel diameter for calculations
int distance=24; //desired distance
int Ttick=360;//total ticks for 1 rotation
float kP=0.5;//Proportional constant
float kI=0.025;//Integral constant
float kD=0.025;// Derivative constant
int error=0;

void forward(int d){
	int FwdTicks=Ttick*d/(wheelDia*PI);//target ticks
	nMotorEncoder(LeftM)=0;
	while(FwdTicks>nMotorEncoder(LeftM)){
	error=FwdTicks-nMotorEncoder(LeftM);
	motor(LeftM)=kP*error;
	motor(RightM)=kP*error;
}
motor(LeftM)=0;
motor(RightM)=0;
error=0;
nMotorEncoder(LeftM)=0;
}
/*
void turnR(){
  resetMotorEncoder(LeftM);
	while(abs(getMotorEncoder(LeftM))<15){
	motor(LeftM)=60;
	motor(RightM)=-60;
}
motor(LeftM)=0;
motor(RightM)=0;
}
void turnL(){
  resetMotorEncoder(LeftM);
	while(abs(getMotorEncoder(LeftM))<15){
	motor(LeftM)=-60;
	motor(RightM)=60;
}
motor(LeftM)=0;
motor(RightM)=0;
}
*/

task main()
{
	int i;
	for(;;){
	forward(distance);
    wait1Msec(500);
	//turnR();
}
}
